INSERT INTO stock values(1, 'TCS', 210, CURRENT_TIMESTAMP);
INSERT INTO stock values(2, 'ITC', 500, CURRENT_TIMESTAMP);
INSERT INTO stock values(3, 'HUL', 600, CURRENT_TIMESTAMP);
INSERT INTO stock values(4, 'APPLE', 120, CURRENT_TIMESTAMP);
INSERT INTO stock values(5, 'HDFC', 410, CURRENT_TIMESTAMP);